### ISSUE TITLE
JS filewatcher does not seem to update files

### ISSUE THREAD

**Issue by robjanssen** [studyportals/product-deploy#46]
FileWatcher: Compressing is disabled
JSWatcher: Watching 231 files under D:\GitHub\Masters
SCSSWatcher: Found 24 main files
SCSSWatcher: Watching 296 files under D:\GitHub\Masters
FileWatcher: Watching 2141 files under D:\GitHub\Masters
JSWatcher: Done
SCSSWatcher: Done
FileWatcher: Done
[JSWatcher
  evt:change
  src:D:\GitHub\Masters\Packages\Academic\Modules\Account\Profile\JS\AccountProfile.js
  dst:D:\Web\Deploy\Masters\Packages\Academic\Modules\Account\Profile\JS\AccountProfile.js
]
[09:03:20] JavaScript compiled.

Adding an `alert("foo")` in the code does not make it show up. You have to do `gulp wk` again in order to get the actual working copy.

**Comment by CZYK** [comment]
Good catch! It misses the base folder and therefore copies the files in the root. I will work on a solution for you.
