### ISSUE TITLE
[Patch] .revision for revision.json

### ISSUE THREAD

**Issue by iliqportals** [studyportals/product-deploy#48]
We no longer need .dependencies,

For backward compatibility, the best action for now is to keep .depenedencies and introduce a new .revision that is the same value of https://github.com/studyportals/product-deploy/blob/master/lib/private/assemble.js#L33

```
revisionJson.dependencies[product] = require('child_process')
			.execSync('git rev-parse HEAD', {
				cwd: opts.from
			})
.toString().trim();
revisionJson.revision = revisionJson.dependencies[product];
```

**Comment by CZYK** [comment]
Already coming up:
https://github.com/studyportals/product-deploy/blob/CZYK-ServiceLayer/lib/private/write-revision.json.js#L46
