### ISSUE TITLE
Integration is not supported // Dynamic Configuration

### ISSUE THREAD

**Issue by iliqportals** [studyportals/product-deploy#55]
Service Layer can be deployed for Integration as well.
I think the best practice would be to check if there is a Configuration folder rather hardcoding the possible values.

**Comment by CZYK** [comment]
I have added `'ING': 'Integration',` and will ship it this Thursday. Dynamic configuration is possible but keep in mind that we use the `env` to decide if a product is running on production-ish (staging, production). This is used to toggle js, css compression on. Or perhaps we should just expose a env var `PRTL_ENABLE_COMPRESSION` to decide if we want to have the files compressed. This way it becomes independent from the env, allowing developers to deploy `Development` with compression enabled.

**Comment by CZYK** [comment]
![image](https://user-images.githubusercontent.com/4997048/30695153-68b49a7a-9ed7-11e7-9971-74542c063c33.png)
