### ISSUE TITLE
'Line separator' setting in PHPstorm potentially causes issues.

### ISSUE THREAD

**Issue by SteveZeeuwe** [studyportals/product-deploy#66]
This setting can be changed at the bottom right corner of the screen.

the file `package.json` often contains changes after running `npm install` while nothing is changed. This is due to the fact that PhpStorm uses the wrong line-endings for this file. The result is that a `git pull` will not work since the file contains open 'changes'.

**Comment by CZYK** [comment]
This is solved in the `.gitattributes` file of the projects by adding the line `package.json eol=lf`.

The easiest way to enforce this change from being applied on your computer is to delete the repository and clone it again.
