### ISSUE TITLE
Progress bar as logging

### ISSUE THREAD

**Issue by iliqportals** [studyportals/product-deploy#76]
When deploying with verbosity level = 1
The console displays
```
[Time] Sass compiled
```
It gets stuck on that message for a while. In the mean time it is running babel.
It would be good to indicate that something is happening right now.
The most friendly way is with a progress bar and/or a Time estimate of when it will complete

**Comment by CZYK** [comment]
Agreed! Let's start with a small iteration:
```
[Time] Sass compiling, this might take a while...
[Time] ass compiled
```
The same counts for js and these messages should be informational.

We could implement the progress bar as part of https://github.com/studyportals/product-deploy/pull/65

**Comment by CZYK** [comment]
I have implemented a nice progress bar. It works great except for Git bash.. 🤔
